// slipwise backend API.
//
// @title           slipwise API
// @version         1.0
// @description     Backend for slipwise — auth, realtime chat, notifications, and betting modules.
// @host            localhost:8080
// @BasePath        /
// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Type "Bearer" followed by a space and the JWT access token.
package main

import (
	"context"
	"errors"
	"log"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"slipwise/internal/admin"
	adminhandler "slipwise/internal/admin/handler"
	adminrepo "slipwise/internal/admin/repository"
	adminservice "slipwise/internal/admin/service"
	"slipwise/internal/auth"
	authhandler "slipwise/internal/auth/handler"
	authRepo "slipwise/internal/auth/repository"
	authservice "slipwise/internal/auth/service"
	bettinghandler "slipwise/internal/betting/handler"
	"slipwise/internal/betting/provider/sportybet"
	bettingrepo "slipwise/internal/betting/repository"
	bettingservice "slipwise/internal/betting/service"
	"slipwise/internal/config"
	db "slipwise/internal/db/generated"
	"slipwise/internal/httpserver"
	"slipwise/internal/mailer"
	"slipwise/internal/notification"
	"slipwise/internal/worker"

	_ "slipwise/docs" // generated by `swag init`, provides the swagger.json the router serves
)

// shutdownTimeout is how long a graceful shutdown waits for in-flight
// requests to finish before forcing the process to exit anyway.
const shutdownTimeout = 10 * time.Second

func main() {
	// Structured logging: every log line from here on is a JSON
	// object (level, message, and whatever key/value fields a call
	// site adds), not a free-text string. This is what makes
	// production logs queryable/filterable in Datadog/CloudWatch instead of grep-only.
	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout, nil)))

	// Step 1: Load environment configuration.
	// If any required environment variable is missing, Load() halts startup immediately
	// and gives us a clean, alphabetized list of what to fix in our .env file.
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config error: %v", err)
	}

	// Step 2: Establish the PostgreSQL connection pool.
	// We use pgxpool instead of database/sql because pgx gives us native PostgreSQL binary protocol,
	// superior performance, and direct support for pgtype (Numeric, UUID, etc.).
	pool := mustConnectDB(cfg.DatabaseURL)
	defer pool.Close()

	// queries wraps our sqlc-generated type-safe database queries.
	queries := db.New(pool)

	// Step 3: Initialize foundational infrastructure services.
	// JWT issuer handles signing access tokens (15-min TTL) and refresh token mechanics.
	jwtIssuer := auth.NewJWTIssuer(cfg.JWTSecret)
	// Resend is our transactional email provider for OTPs and verification emails.
	resendMailer := mailer.NewResendMailer(cfg.ResendAPIKey, cfg.ResendFromAddress)

	// Step 4: Wire the Auth domain (Repository -> Service -> Handler).
	// Strict Layered Architecture: Handlers know only Services; Services know Repositories & Domain models.
	authRepo := authRepo.NewAuthRepository(queries)
	authSvc := authservice.NewAuthService(authRepo, jwtIssuer, resendMailer, cfg.GoogleClientID, cfg.FeedbackEmail)
	authH := authhandler.NewAuthHandler(authSvc)

	// Step 5: Wire the Betting domain.
	// The CloudflareClient proxies requests through a Cloudflare Worker to avoid WAF / IP blocks
	// while querying bookmaker endpoints.
	cfClient := worker.NewCloudflareClient(cfg.CloudflareWorkerURL)
	sportyProvider := sportybet.NewProvider(cfClient)

	bettingRepo := bettingrepo.NewRepository(pool)
	bettingSvc := bettingservice.NewBettingService(
		bettingRepo,
		map[string]bettingservice.TicketProvider{
			"SPORTYBET": sportyProvider,
		},
	)
	bettingH := bettinghandler.NewBettingHandler(bettingSvc)

	// Step 6: Wire the Admin domain (Repository -> Service -> Handler).
	// RequireAdmin middleware is built here (where queries lives) and passed
	// into Handlers as a pre-wired echo.MiddlewareFunc — the router never touches the DB.
	adminRepo := adminrepo.New(queries)
	adminSvc := adminservice.New(adminRepo)
	adminH := adminhandler.New(adminSvc)
	adminMiddleware := admin.RequireAdmin(queries)

	// Step 6: Spawn background workers.
	// Background Worker 1: The Scavenger (Orphan Cleanup Job).
	// Runs periodically in a background goroutine to clean up booking codes that were previewed
	// or tracked but later orphaned/abandoned by all users.
	cleanupJob := worker.NewCleanupJob(bettingSvc)
	go cleanupJob.Start(context.Background())

	// Initialize Firebase Cloud Messaging (FCM) for push notifications (e.g. settlement alerts).
	fcmSvc, err := notification.NewFCMService(context.Background(), cfg.FirebaseCredentialsJSON)
	if err != nil {
		slog.Error("fcm initialization failed (invalid FIREBASE_CREDENTIALS_JSON)", "error", err)
		os.Exit(1)
	}

	// Background Worker 2: The Settlement Poller & Live Evaluator.
	// Periodically queries the Cloudflare live firehose, decodes live match scores,
	// updates database match states, and triggers push notifications when tickets win or lose.
	poller := worker.NewPoller(cfClient, bettingRepo, worker.NewLiveEvaluator(bettingRepo, fcmSvc), 60*time.Second)
	go poller.Start(context.Background())

	// Step 7: Bundle handlers and construct the Echo router.
	handlers := httpserver.Handlers{
		Auth:            authH,
		Betting:         bettingH,
		Admin:           adminH,
		AdminMiddleware: adminMiddleware,
		Poller:          poller,
	}

	r := httpserver.NewRouter(handlers, jwtIssuer, cfg.AllowedOrigins, cfg.TrustedProxyCIDRs, cfg.CronSecret)

	// Step 8: Configure and start the standard library HTTP Server.
	srv := &http.Server{
		Addr:    ":" + cfg.Port,
		Handler: r,
	}

	// Run the server in a goroutine so main() stays free to listen for
	// a shutdown signal below. ListenAndServe blocks until the server
	// stops; ErrServerClosed is the expected error on a clean
	// Shutdown() call, not a real failure.
	go func() {
		slog.Info("server starting", "port", cfg.Port)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("server error: %v", err)
		}
	}()

	// Step 9: Graceful Shutdown orchestration.
	// Block until the OS asks us to stop — Ctrl+C locally (SIGINT), or
	// SIGTERM from whatever's managing the process in staging/prod
	// (systemd, Docker, Kubernetes, Railway). Without this,
	// every deploy/restart would abruptly sever database transactions and in-flight HTTP requests.
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt, syscall.SIGTERM)
	<-quit

	slog.Info("shutdown signal received, draining in-flight requests")

	// Allow up to shutdownTimeout (10s) for active requests to finish before hard exit.
	ctx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		log.Fatalf("forced shutdown after %s: %v", shutdownTimeout, err)
	}

	slog.Info("server exited cleanly")
}
