// main.go
// Sportloga backend API.
//
// @title           Sportloga API
// @version         1.0
// @description     Backend for Sportloga — auth, realtime chat, notifications, and betting modules.
// @host            localhost:8080
// @BasePath        /
// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Type "Bearer" followed by a space and the JWT access token.
package main

import (
	"log"
	"net/http"
	"os"

	"sportloga/internal/auth"
	authhandler "sportloga/internal/auth/handler"
	"sportloga/internal/auth/repository"
	"sportloga/internal/auth/service"
	db "sportloga/internal/db/generated"
	"sportloga/internal/httpserver"
	"sportloga/internal/mailer"

	"github.com/joho/godotenv"

	_ "sportloga/docs" // generated by `swag init`, provides the swagger.json the router serves
)

func main() {
	// Loads .env into the process's environment if present. In
	// staging/prod there typically is no .env file — real env vars are
	// injected by the platform — so a missing file here is not an
	// error, only a missing *variable* (caught by mustGetEnv below) is.
	if err := godotenv.Load(); err != nil {
		log.Println("no .env file found, reading from process environment")
	}

	pool := mustConnectDB()
	defer pool.Close()

	queries := db.New(pool)

	jwtIssuer := auth.NewJWTIssuer(mustGetEnv("JWT_SECRET"))
	resendMailer := mailer.NewResendMailer(mustGetEnv("RESEND_API_KEY"), mustGetEnv("RESEND_FROM_ADDRESS"))

	authRepo := repository.NewAuthRepository(queries)
	authSvc := service.NewAuthService(authRepo, jwtIssuer, resendMailer)
	authH := authhandler.NewAuthHandler(authSvc)

	// As each new domain (realtime, notifications, betting...) gets its
	// own repo/service/handler, wire it here and add it to Handlers below.
	// Route mounting itself never happens in this file — see
	// internal/httpserver/router.go.
	handlers := httpserver.Handlers{
		Auth: authH,
	}

	r := httpserver.NewRouter(handlers, jwtIssuer)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("server running on port %s\n", port)
	log.Fatal(http.ListenAndServe(":"+port, r))
}
