// Sportloga backend API.
//
// @title           Sportloga API
// @version         1.0
// @description     Backend for Sportloga — auth, realtime chat, notifications, and betting modules.
// @host            localhost:8080
// @BasePath        /
// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Type "Bearer" followed by a space and the JWT access token.
package main

import (
	"log"
	"net/http"

	"sportloga/internal/auth"
	authhandler "sportloga/internal/auth/handler"
	"sportloga/internal/auth/repository"
	"sportloga/internal/auth/service"
	"sportloga/internal/config"
	db "sportloga/internal/db/generated"
	"sportloga/internal/httpserver"
	"sportloga/internal/mailer"

	_ "sportloga/docs" // generated by `swag init`, provides the swagger.json the router serves
)

func main() {
	// Loads and validates every required env var in one place, up
	// front. If anything's missing, this fails immediately with the
	// full list — not one var at a time, deep into startup.
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config error: %v", err)
	}

	pool := mustConnectDB(cfg.DatabaseURL)
	defer pool.Close()

	queries := db.New(pool)

	jwtIssuer := auth.NewJWTIssuer(cfg.JWTSecret)
	resendMailer := mailer.NewResendMailer(cfg.ResendAPIKey, cfg.ResendFromAddress)

	authRepo := repository.NewAuthRepository(queries)
	authSvc := service.NewAuthService(authRepo, jwtIssuer, resendMailer)
	authH := authhandler.NewAuthHandler(authSvc)

	// As each new domain (realtime, notifications, betting...) gets its
	// own repo/service/handler, wire it here and add it to Handlers below.
	// Route mounting itself never happens in this file — see
	// internal/httpserver/router.go.
	handlers := httpserver.Handlers{
		Auth: authH,
	}

	r := httpserver.NewRouter(handlers, jwtIssuer)

	log.Printf("server running on port %s\n", cfg.Port)
	log.Fatal(http.ListenAndServe(":"+cfg.Port, r))
}